import { EventHeader } from "@/components/EventHeader";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { Activity, Award, BarChart3, Loader2, Radio, Sparkles, Trophy, UsersRound } from "lucide-react";
import { useLocation } from "wouter";

const tone = ["gold", "teal", "coral", "violet"];

export default function LiveWall() {
  const [, setLocation] = useLocation();
  const board = trpc.event.liveBoard.useQuery(undefined, { refetchInterval: 3500, refetchOnWindowFocus: true });
  const totals = board.data?.totals;
  return <div className="live-shell"><EventHeader compact /><main className="container live-page"><section className="live-page__intro"><div><div className="live-kicker"><Radio size={15} className="pulse-dot" /> Auto-updating event display</div><h1>Discovery in <em>motion.</em></h1><p>Every point, approved idea, and shared voice helps tell the story of ICT Welcome Day.</p></div><Button className="ghost-on-dark" variant="outline" onClick={() => setLocation("/")}>Return to activities</Button></section>
    <section className="live-command"><div className="live-command__copy"><p>EVENT CONTROL STREAM</p><h2>Every choice becomes part of the story.</h2><span>Watch quests, votes, and approved creations move across the day.</span></div><div className="live-metrics"><div><UsersRound size={19} /><strong>{totals?.participantCount ?? 0}</strong><span>Passports</span></div><div><Activity size={19} /><strong>{totals?.completionCount ?? 0}</strong><span>Challenges</span></div><div><Sparkles size={19} /><strong>{totals?.totalPoints ?? 0}</strong><span>Points</span></div><div><Award size={19} /><strong>{totals?.activityCount ?? 9}</strong><span>Open activities</span></div></div></section>
    {board.isLoading ? <div className="loading-panel"><Loader2 className="animate-spin" /> Preparing the live wall…</div> : <section className="live-grid"><div className="live-card leaderboard-card"><div className="live-card__heading"><div><p className="section-kicker">Explorer spotlight</p><h2>Passport leaders</h2></div><Trophy size={22} /></div>{board.data?.participants.length ? <div className="leader-list">{board.data.participants.map((participant, index) => <div className="leader-row" key={participant.id}><b className={`leader-rank leader-rank--${index + 1}`}>{index + 1}</b><div className={`avatar-orb avatar-orb--${participant.avatarColor}`}>{participant.displayName.slice(0, 1).toUpperCase()}</div><div className="leader-name"><strong>{participant.displayName}</strong><span>Grades {participant.gradeBand} · {participant.completedCount}/{board.data.totals.activityCount} activities · {participant.badgeCount} badges</span><div className="leader-progress"><span style={{ width: `${Math.min(100, (participant.completedCount / Math.max(1, board.data.totals.activityCount)) * 100)}%` }} /></div>{participant.badges.length > 0 && <small className="leader-badges">{participant.badges.slice(0, 2).join(" · ")}</small>}</div><em>{participant.points} pts</em></div>)}</div> : <p className="live-empty">The first explorers will appear here as they open their passports.</p>}</div>
      <div className="live-card word-card"><div className="live-card__heading"><div><p className="section-kicker">Student voice</p><h2>What ICT means to us</h2></div><Sparkles size={22} /></div><div className="word-cloud">{board.data?.words.length ? board.data.words.map((word, index) => <span key={`${word}-${index}`} className={`word-chip word-chip--${tone[index % tone.length]}`}>{word}</span>) : <p className="live-empty">Approved reflections will bloom here.</p>}</div></div>
      <div className="live-card vote-card"><div className="live-card__heading"><div><p className="section-kicker">Future Tech Vote</p><h2>Skills students want</h2></div><BarChart3 size={22} /></div>{board.data?.votes.length ? <div className="vote-bars">{board.data.votes.map(vote => { const max = Math.max(...(board.data?.votes.map(item => item.count) ?? [1])); return <div className="vote-line" key={vote.option}><div><span>{vote.option}</span><b>{vote.count}</b></div><div className="vote-track"><span style={{ width: `${(vote.count / max) * 100}%` }} /></div></div>; })}</div> : <p className="live-empty">Votes will appear as explorers share their future goals.</p>}</div>
      <div className="live-card icebreaker-live-card"><div className="live-card__heading"><div><p className="section-kicker">Mentimeter-style icebreaker</p><h2>Welcome Day live pulse</h2></div><Radio size={22} /></div><div className="live-poll-grid">{board.data?.icebreakerPolls.map(poll => <div className="live-poll-block" key={poll.key}><p>{poll.question}</p>{poll.votes.length ? <div className="vote-bars">{poll.votes.slice(0, 4).map(vote => { const max = Math.max(...poll.votes.map(item => item.count)); return <div className="vote-line" key={vote.option}><div><span>{vote.option}</span><b>{vote.count}</b></div><div className="vote-track"><span style={{ width: `${(vote.count / max) * 100}%` }} /></div></div>; })}</div> : <small>Waiting for the first answers…</small>}</div>)}</div></div>
      <div className="live-card gallery-card"><div className="live-card__heading"><div><p className="section-kicker">Approved gallery</p><h2>Made by our explorers</h2></div><Badge>Staff reviewed</Badge></div>{board.data?.recentWork.length ? <div className="gallery-stream">{board.data.recentWork.map(work => <article className="gallery-item" key={work.id}>{work.fileUrl && work.mimeType?.startsWith("image/") ? <img src={work.fileUrl} alt={`${work.name}'s ${work.title} submission`} /> : work.fileUrl && work.mimeType?.startsWith("video/") ? <video controls preload="metadata" src={work.fileUrl} aria-label={`${work.name}'s ${work.title} video submission`} /> : <div className="gallery-file"><Sparkles size={23} /><span>{work.fileName ?? work.title}</span></div>}<div><strong>{work.name}</strong><p>{work.body || work.title}</p></div></article>)}</div> : <p className="live-empty">Approved creative work will appear here.</p>}</div>
    </section>}
  </main></div>;
}
