import { useAuth } from "@/_core/hooks/useAuth";
import DashboardLayout from "@/components/DashboardLayout";
import { AlertDialog, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from "@/components/ui/alert-dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { startLogin } from "@/const";
import { trpc } from "@/lib/trpc";
import { Check, ClipboardCheck, Download, ExternalLink, FileText, Loader2, Maximize2, MonitorUp, RotateCcw, ShieldAlert, ShieldCheck, Sparkles, UsersRound, X } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";

type ResourceDraft = { url: string; label: string };

const csvCell = (value: unknown) => `"${String(value ?? "").replaceAll('"', '""')}"`;

function StaffContent() {
  const { user, loading } = useAuth();
  const utils = trpc.useUtils();
  const overview = trpc.staff.overview.useQuery(undefined, { enabled: Boolean(user?.role === "admin" || user?.role === "teacher"), refetchInterval: 5000 });
  const queue = trpc.staff.moderationQueue.useQuery(undefined, { enabled: Boolean(user?.role === "admin"), refetchInterval: 5000 });
  const exportResults = trpc.staff.exportResults.useQuery(undefined, { enabled: false });
  const [notes, setNotes] = useState<Record<number, string>>({});
  const [drafts, setDrafts] = useState<Record<number, ResourceDraft>>({});
  const [resetOpen, setResetOpen] = useState(false);
  const [resetConfirmation, setResetConfirmation] = useState("");
  const [teacherEmail, setTeacherEmail] = useState("");
  const [teacherSection, setTeacherSection] = useState<"boys" | "girls" | "all">("boys");
  const [participantSearch, setParticipantSearch] = useState("");
  const teacherAccess = trpc.staff.teacherAccess.useQuery(undefined, { enabled: Boolean(user?.role === "admin") });

  useEffect(() => {
    if (!overview.data) return;
    setDrafts(Object.fromEntries(overview.data.activities.map(activity => [activity.id, { url: activity.resourceUrl ?? "", label: activity.resourceLabel ?? "" }])));
  }, [overview.data]);

  const refreshEventViews = () => {
    utils.staff.overview.invalidate();
    utils.event.liveBoard.invalidate();
    utils.event.activities.invalidate();
  };
  const moderate = trpc.staff.moderate.useMutation({ onSuccess: () => { toast.success("Submission status updated."); utils.staff.moderationQueue.invalidate(); refreshEventViews(); }, onError: error => toast.error(error.message) });
  const updateResource = trpc.staff.updateResource.useMutation({ onSuccess: () => { toast.success("Teacher resource updated."); refreshEventViews(); }, onError: error => toast.error(error.message) });
  const setParticipantVisibility = trpc.staff.setParticipantVisibility.useMutation({ onSuccess: () => { toast.success("Live-wall visibility updated."); refreshEventViews(); }, onError: error => toast.error(error.message) });
  const resetResults = trpc.staff.resetResults.useMutation({ onSuccess: result => { toast.success(`${result.cleared} subject result${result.cleared === 1 ? "" : "s"} cleared. Student records remain available.`); setResetOpen(false); setResetConfirmation(""); refreshEventViews(); }, onError: error => toast.error(error.message) });
  const saveTeacherAccess = trpc.staff.saveTeacherAccess.useMutation({ onSuccess: () => { toast.success("Teacher access saved. The teacher can sign in with this email address."); setTeacherEmail(""); teacherAccess.refetch(); }, onError: error => toast.error(error.message) });
  const setTeacherAccessStatus = trpc.staff.setTeacherAccessStatus.useMutation({ onSuccess: () => { toast.success("Teacher access updated."); teacherAccess.refetch(); }, onError: error => toast.error(error.message) });

  const downloadResults = async () => {
    const response = await exportResults.refetch();
    const rows = response.data ?? [];
    if (!rows.length) return toast.message("There are no completed subject quizzes to export yet.");
    const csv = ["Student name,Grade band,Subject,Score out of 3,Points,Completed at", ...rows.map(row => [row.name, `Grades ${row.gradeBand}`, row.subject, row.score, row.points, new Date(row.completedAt).toLocaleString()].map(csvCell).join(","))].join("\n");
    const link = document.createElement("a");
    link.href = URL.createObjectURL(new Blob([csv], { type: "text/csv;charset=utf-8" }));
    link.download = `tfa-welcome-day-results-${new Date().toISOString().slice(0, 10)}.csv`;
    link.click();
    URL.revokeObjectURL(link.href);
    toast.success(`${rows.length} subject result${rows.length === 1 ? "" : "s"} exported.`);
  };

  if (loading) return <div className="staff-loading"><Loader2 className="animate-spin" /> Checking staff access…</div>;
  if (!user) return <div className="staff-login"><ShieldCheck size={36} /><h1>Staff event control</h1><p>Sign in with an authorised school account to manage live results, student visibility, and ICT resources.</p><Button className="navy-button" onClick={() => startLogin()}>Sign in to control room</Button></div>;
  if (user.role !== "admin" && user.role !== "teacher") return <div className="staff-login"><ShieldCheck size={36} /><h1>Staff access required</h1><p>Your account is signed in, but it has not yet been assigned a teacher or administrator role.</p></div>;

  const totals = overview.data?.totals;
  const visibleParticipants = overview.data?.participants.filter(participant => `${participant.displayName} ${participant.gradeBand} ${participant.eventSection} ${participant.classLabel ?? ""}`.toLowerCase().includes(participantSearch.trim().toLowerCase())) ?? [];
  return <div className="staff-content">
    <div className="staff-heading"><div><p className="section-kicker">The First Academy School · ICT Department</p><h1>Welcome Day <em>Control Room</em></h1><p>Manage {user.staffSection === "all" ? "all event sections" : `${user.staffSection} section`} results, follow participation, and prepare the live display.</p></div><a href={user.staffSection === "all" ? "/live" : `/live?section=${user.staffSection}`} target="_blank" rel="noreferrer" className="staff-display-link"><MonitorUp size={17} /> Open live display <ExternalLink size={14} /></a></div>
    <section className="staff-stat-grid"><div><UsersRound size={19} /><strong>{totals?.participants ?? 0}</strong><span>Participants</span></div><div><ClipboardCheck size={19} /><strong>{totals?.completions ?? 0}</strong><span>Subject results</span></div><div><FileText size={19} /><strong>{totals?.pendingSubmissions ?? 0}</strong><span>Awaiting review</span></div><div><Sparkles size={19} /><strong>{totals?.activeActivities ?? 0}</strong><span>Active subjects</span></div></section>
    <section className="staff-section staff-results-tools"><div className="staff-section__heading"><div><p className="section-kicker">Event-day essentials</p><h2>Results management</h2></div><span>Staff-only controls</span></div><div className="staff-results-tools__grid"><div><Download size={22} /><h3>Export current results</h3><p>Download a CSV with student name, grade band, subject, score, points, and completion time.</p><Button className="navy-button" disabled={exportResults.isFetching} onClick={downloadResults}>{exportResults.isFetching ? <Loader2 className="animate-spin" size={16} /> : <Download size={16} />} Export CSV</Button></div><div className="staff-reset-card"><ShieldAlert size={22} /><h3>Reset subject results</h3><p>Clears the five subject-quiz scores from the board and learning records. Student names and access codes are retained.</p><AlertDialog open={resetOpen} onOpenChange={setResetOpen}><AlertDialogTrigger asChild><Button variant="outline" className="reset-button"><RotateCcw size={16} /> Reset results</Button></AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Reset all subject results?</AlertDialogTitle><AlertDialogDescription>This cannot be undone. Type <strong>RESET RESULTS</strong> to clear completed subject quizzes while keeping student records and access codes.</AlertDialogDescription></AlertDialogHeader><Label htmlFor="result-reset-confirmation">Confirmation phrase</Label><Input id="result-reset-confirmation" value={resetConfirmation} onChange={event => setResetConfirmation(event.target.value)} placeholder="RESET RESULTS" autoComplete="off" /><AlertDialogFooter><AlertDialogCancel disabled={resetResults.isPending}>Cancel</AlertDialogCancel><Button className="reset-confirm-button" disabled={resetConfirmation !== "RESET RESULTS" || resetResults.isPending} onClick={() => resetResults.mutate({ confirmation: "RESET RESULTS" })}>{resetResults.isPending ? <Loader2 className="animate-spin" size={16} /> : <RotateCcw size={16} />} Clear subject results</Button></AlertDialogFooter></AlertDialogContent></AlertDialog></div></div><a className="staff-projector-link" href="/live?projector=1" target="_blank" rel="noreferrer"><MonitorUp size={17} /><span><strong>Open protected projector display</strong><small>This display shortcut works only for signed-in event administrators.</small></span><Maximize2 size={16} /></a></section>
    {user.role === "admin" && <section className="staff-section"><div className="staff-section__heading"><div><p className="section-kicker">Individual teacher sign-in</p><h2>Teacher access</h2></div><span>Assign a school email to a section</span></div><div className="resource-fields"><div><Label htmlFor="teacher-access-email">Teacher school email</Label><Input id="teacher-access-email" value={teacherEmail} onChange={event => setTeacherEmail(event.target.value)} placeholder="teacher@school.ae" type="email" /></div><div><Label htmlFor="teacher-access-section">Control-room scope</Label><select id="teacher-access-section" value={teacherSection} onChange={event => setTeacherSection(event.target.value as typeof teacherSection)}><option value="boys">Boys section</option><option value="girls">Girls section</option><option value="all">All sections (administrator-level view)</option></select></div><Button className="navy-button" disabled={!teacherEmail.trim() || saveTeacherAccess.isPending} onClick={() => saveTeacherAccess.mutate({ email: teacherEmail, staffSection: teacherSection })}>{saveTeacherAccess.isPending ? <Loader2 className="animate-spin" size={16} /> : <ShieldCheck size={16} />} Save teacher access</Button></div><div className="participant-control-list">{teacherAccess.data?.map(grant => <article className="participant-control-row" key={grant.id}><div><h3>{grant.email}</h3><p>{grant.staffSection} section scope · {grant.isActive ? "Active" : "Paused"}</p></div><Button size="sm" variant={grant.isActive ? "outline" : "default"} className={grant.isActive ? "hide-button" : "approve-button"} disabled={setTeacherAccessStatus.isPending} onClick={() => setTeacherAccessStatus.mutate({ id: grant.id, isActive: !Boolean(grant.isActive) })}>{grant.isActive ? "Pause access" : "Restore access"}</Button></article>) ?? <div className="staff-empty"><ShieldCheck size={24} /><p>Add each teacher’s school email to give them their own sign-in access.</p></div>}</div></section>}
    <section className="staff-section"><div className="staff-section__heading"><div><p className="section-kicker">Review-friendly queue</p><h2>Creative submissions</h2></div><span>{queue.data?.length ?? 0} pending</span></div>{queue.isLoading ? <div className="staff-empty"><Loader2 className="animate-spin" /> Loading submissions…</div> : queue.data?.length ? <div className="moderation-list">{queue.data.map(item => <article className="moderation-row" key={item.submission.id}><div className="moderation-file">{item.submission.fileUrl && item.submission.mimeType?.startsWith("image/") ? <img src={item.submission.fileUrl} alt={`${item.displayName}'s submission`} /> : <FileText size={22} />}</div><div className="moderation-work"><div><span>{item.activityTitle ?? "Digital Discovery"}</span><h3>{item.displayName} <small>· Grades {item.gradeBand}</small></h3></div>{item.submission.body && <p>{item.submission.body}</p>}{item.submission.fileUrl && <a href={item.submission.fileUrl} target="_blank" rel="noreferrer">Open attached evidence <ExternalLink size={13} /></a>}</div><div className="moderation-actions"><Textarea value={notes[item.submission.id] ?? ""} onChange={event => setNotes(current => ({ ...current, [item.submission.id]: event.target.value }))} placeholder="Optional staff note" maxLength={300} /><div><Button variant="outline" size="sm" disabled={moderate.isPending} onClick={() => moderate.mutate({ submissionId: item.submission.id, status: "rejected", adminNote: notes[item.submission.id] })}><X size={15} /> Reject</Button><Button size="sm" className="approve-button" disabled={moderate.isPending} onClick={() => moderate.mutate({ submissionId: item.submission.id, status: "approved", adminNote: notes[item.submission.id] })}><Check size={15} /> Approve</Button></div></div></article>)}</div> : <div className="staff-empty"><Sparkles size={24} /><p>No submissions are waiting. The simplified subject-quiz experience needs no moderation for scores.</p></div>}</section>
    <section className="staff-section"><div className="staff-section__heading"><div><p className="section-kicker">Record & display management</p><h2>Find a student and manage live-board visibility</h2></div><span>Search by name or class, for example Boy 7F</span></div><div className="resource-fields"><div><Label htmlFor="participant-search">Search this teacher scope</Label><Input id="participant-search" value={participantSearch} onChange={event => setParticipantSearch(event.target.value)} placeholder="Name, grade group, or Boy 7F" /></div></div><div className="participant-control-list">{visibleParticipants.length ? visibleParticipants.map(participant => <article className="participant-control-row" key={participant.id}><div><h3>{participant.displayName} <small>· Grades {participant.gradeBand} · {participant.classLabel ?? participant.eventSection}</small></h3><p>{participant.completedCount}/{participant.activityCount} ICT studios completed · {participant.totalPoints} points</p></div><Button size="sm" variant={participant.isActive ? "outline" : "default"} className={participant.isActive ? "hide-button" : "approve-button"} disabled={setParticipantVisibility.isPending} onClick={() => setParticipantVisibility.mutate({ participantId: participant.id, isActive: !Boolean(participant.isActive) })}>{participant.isActive ? "Hide from live wall" : "Show on live wall"}</Button></article>) : <div className="staff-empty"><UsersRound size={24} /><p>{overview.data?.participants.length ? "No student record matches this search." : "Participant visibility controls will appear here when students join."}</p></div>}</div></section>
    <section className="staff-section"><div className="staff-section__heading"><div><p className="section-kicker">Teacher-replaceable content</p><h2>Activity resources</h2></div><span>{totals?.activeActivities ?? 0} active subjects</span></div><div className="resource-list">{overview.data?.activities.map(activity => { const draft = drafts[activity.id] ?? { url: "", label: "" }; return <article className="resource-row" key={activity.id}><div><span className={`zone-tag zone-tag--${activity.zone}`}>{activity.zone}</span><h3>{activity.title}</h3><p>{activity.gradeHint}</p></div><div className="resource-fields"><div><Label htmlFor={`label-${activity.id}`}>Link label</Label><Input id={`label-${activity.id}`} value={draft.label} onChange={event => setDrafts(current => ({ ...current, [activity.id]: { ...draft, label: event.target.value } }))} /></div><div><Label htmlFor={`url-${activity.id}`}>Resource URL</Label><Input id={`url-${activity.id}`} value={draft.url} onChange={event => setDrafts(current => ({ ...current, [activity.id]: { ...draft, url: event.target.value } }))} /></div><Button size="sm" className="navy-button" disabled={updateResource.isPending || !draft.url || !draft.label} onClick={() => updateResource.mutate({ activityId: activity.id, resourceUrl: draft.url, resourceLabel: draft.label })}>Save</Button></div></article>; })}</div></section>
  </div>;
}

export default function Staff() { return <DashboardLayout><StaffContent /></DashboardLayout>; }
